name: Python application

on:
  push:
    branches: "main"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      FLASK_APP: microblog.py
      FLASK_ENV: development
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-19.04 ]
        python-version: [ "3.7", "3.8", "3.9" ]
    #runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Create a virtual environment
      run: |
          python3 -m venv venv
          echo "python3 successfully installed"

    - name:  Activate venv
      run: |
          source venv/bin/activate
          echo "venv successfully activated"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        echo "Install dependencies"
    - name: Set the environment variables
      run:  |
        export FLASK_APP=$env.FLASK_APP
        export FLASK_ENV=$env.FLASK_ENV
        echo "Set the environment variables"
    - name: Initialize the database
      run: |
        flask db upgrade
        echo "Initialize the database"
    - name: Run the tests
      run: |
        pytest tests.py
        echo "Run the tests"

#Konstantin Piatigorskii